language: c
dist: bionic
sudo: false
compiler:
- gcc
addons:
  sonarcloud:
    organization: pietrop88-github
script:
- cmake -DTARGET_GROUP=test .
- build-wrapper-linux-x86-64 --out-dir bw-output make
- ctest --verbose
- sonar-scanner