language: c
dist: bionic
sudo: false
compiler:
- gcc
addons:
  sonarcloud:
    organization: pietrop88-github
script:
- mkdir build
- cd build
- cmake -DTARGET_GROUP=test ..
- cd ..
- build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
- cd build && ctest && cd ..
- cd build && ../coverage_ci_sonar.sh && cd ..
- sonar-scanner